"use client";

import { useRef, useState, useCallback, useEffect } from "react";
import Link from "next/link";
import { Send, Sparkles, Paperclip, X, ChevronDown } from "lucide-react";
import { cn } from "@/lib/utils";

// ---------------------------------------------------------------------------
// Available OpenRouter models
// ---------------------------------------------------------------------------

export const AVAILABLE_MODELS = [
  { id: "deepseek/deepseek-chat-v3-0324", label: "DeepSeek V3", isDefault: true },
  { id: "google/gemini-2.5-flash-preview-05-20", label: "Gemini 2.5 Flash" },
  { id: "openai/gpt-4o", label: "GPT-4o" },
  { id: "anthropic/claude-sonnet-4-5", label: "Claude Sonnet 4.5" },
  { id: "meta-llama/llama-4-scout", label: "Llama 4 Scout" },
  { id: "mistralai/mistral-large", label: "Mistral Large" },
];

// Default suggestions — always shown for test user
const DEFAULT_SUGGESTIONS = [
  "x Show me a comparison between sales made in January to May in the year 2026",
  "x Compare monthly sales vs expenses over time",
  "x Show me a months vs sales comparison diagram in area chart",
  "x Compare department budgets with their total operational expenses",
  "x Show total sales generated by each Associate or Senior Associate with bar chart",
  "x Show the breakdown of expenses by category in pie chart",
  "x Show a scatter chart of employees salaries",
  "x Show the monthly sales growth for 2026",
  "x What is the total project budget allocated to each department, grouped by project status",
];

export interface UploadedData {
  uploadId: string;
  fileName: string;
  columns: string[];
  rowCount: number;
  sampleRows: any[];
}

interface ChatInputProps {
  onSubmit: (question: string) => void;
  disabled?: boolean;
  showSuggestions?: boolean;
  isThinking?: boolean;
  onStop?: () => void;
  isTestUser?: boolean;
  uploadedData?: UploadedData | null;
  onUpload?: (data: UploadedData) => void;
  onClearUpload?: () => void;
}

export function ChatInput({
  onSubmit,
  disabled = false,
  showSuggestions = false,
  isThinking = false,
  onStop,
  isTestUser = false,
  uploadedData,
  onUpload,
  onClearUpload,
}: ChatInputProps) {
  const [value, setValue] = useState("");
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [userTemplates, setUserTemplates] = useState<string[]>([]);
  const [uploading, setUploading] = useState(false);
  const [uploadError, setUploadError] = useState("");

  // Load user templates (skip for test user)
  useEffect(() => {
    if (isTestUser) return;
    const BACKEND_URL = process.env.NEXT_PUBLIC_BACKEND_URL || "http://localhost:3002";

    // We need the token from localStorage (auth-storage)
    try {
      const authRaw = localStorage.getItem("auth-storage");
      if (!authRaw) return;
      const authData = JSON.parse(authRaw);
      const token = authData?.state?.accessToken;
      if (!token) return;

      fetch(`${BACKEND_URL}/api/templates`, {
        headers: { Authorization: `Bearer ${token}` },
      })
        .then((r) => (r.ok ? r.json() : []))
        .then((templates: any[]) => {
          setUserTemplates(templates.map((t) => t.text));
        })
        .catch(() => { });
    } catch { }
  }, [isTestUser]);

  // Combine suggestions: user templates first, then defaults
  const suggestions = isTestUser ? DEFAULT_SUGGESTIONS : userTemplates;

  const handleSubmit = useCallback(() => {
    const trimmed = value.trim();
    if (!trimmed || disabled) return;
    onSubmit(trimmed);
    setValue("");
    if (textareaRef.current) {
      textareaRef.current.style.height = "auto";
    }
  }, [value, disabled, onSubmit]);

  const handleSuggestionClick = useCallback((s: string) => {
    setValue(s);
    if (textareaRef.current) {
      textareaRef.current.focus();
      setTimeout(() => {
        if (textareaRef.current) {
          textareaRef.current.style.height = "auto";
          textareaRef.current.style.height = `${Math.min(textareaRef.current.scrollHeight, 180)}px`;
        }
      }, 0);
    }
  }, []);

  function handleKeyDown(e: React.KeyboardEvent<HTMLTextAreaElement>) {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSubmit();
    }
  }

  function handleInput(e: React.ChangeEvent<HTMLTextAreaElement>) {
    setValue(e.target.value);
    const el = e.target;
    el.style.height = "auto";
    el.style.height = `${Math.min(el.scrollHeight, 180)}px`;
  }

  async function handleFileChange(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file || !onUpload) return;

    setUploading(true);
    setUploadError("");

    try {
      const { uploadFile } = await import("@/app/actions/ai-chat");
      const formData = new FormData();
      formData.append("file", file);
      const result = await uploadFile(formData);

      if (result.success) {
        onUpload({
          uploadId: result.uploadId,
          fileName: result.fileName,
          columns: result.columns,
          rowCount: result.rowCount,
          sampleRows: result.sampleRows,
        });
      } else {
        setUploadError(result.error || "Upload failed.");
      }
    } catch (err: any) {
      setUploadError(err.message || "Upload failed.");
    } finally {
      setUploading(false);
      if (fileInputRef.current) fileInputRef.current.value = "";
    }
  }

  return (
    <div className="flex flex-col gap-3">
      {/* Suggestion chips — only when conversation is empty */}
      {showSuggestions && (
        <div className="max-h-[260px] md:max-h-[160px] overflow-y-auto scrollbar-thin w-full px-1">
          <div className="flex flex-wrap justify-center gap-2 py-1">
            {suggestions.length > 0 ? (
              suggestions.map((s) => (
                <button
                  key={s}
                  onClick={() => handleSuggestionClick(s)}
                  disabled={disabled}
                  className="rounded-full border border-white/10 bg-white/[0.04] px-3.5 py-1.5 text-xs text-white/50 transition-all hover:border-white/20 hover:bg-white/[0.08] hover:text-white/80 disabled:cursor-not-allowed disabled:opacity-30"
                >
                  {s}
                </button>
              ))
            ) : !isTestUser ? (
              <Link
                href="/templates"
                className="rounded-full border border-dashed border-white/20 bg-white/[0.02] px-4 py-2 text-xs text-white/40 transition-all hover:border-white/40 hover:bg-white/[0.05] hover:text-white/70 flex items-center gap-1 cursor-pointer"
              >
                <span>+ add template</span>
              </Link>
            ) : null}
          </div>
        </div>
      )}

      {/* Uploaded file banner */}
      {uploadedData && (
        <div className="flex items-center gap-2 rounded-xl border border-blue-500/20 bg-blue-500/10 px-3 py-2">
          <div className="flex-1 min-w-0">
            <span className="text-xs font-medium text-blue-300 truncate">{uploadedData.fileName}</span>
            <span className="ml-2 text-xs text-blue-400/60">{uploadedData.rowCount.toLocaleString()} rows · {uploadedData.columns.length} columns</span>
          </div>
          {onClearUpload && (
            <button
              onClick={onClearUpload}
              className="size-5 shrink-0 flex items-center justify-center rounded-full text-blue-400/60 hover:text-blue-300 hover:bg-blue-500/20 transition-colors"
              title="Remove uploaded file"
            >
              <X className="size-3" />
            </button>
          )}
        </div>
      )}

      {/* Upload error */}
      {uploadError && (
        <div className="rounded-xl border border-red-500/20 bg-red-500/10 px-3 py-2 text-xs text-red-400">
          {uploadError}
        </div>
      )}

      {/* Input container */}
      <div
        className={cn(
          "relative flex items-end gap-3 rounded-2xl border px-4 py-3 transition-all duration-200",
          disabled && !isThinking
            ? "border-white/[0.06] bg-white/[0.02] opacity-60"
            : "border-white/10 bg-white/[0.05] focus-within:border-blue-500/40 focus-within:bg-white/[0.07] focus-within:ring-1 focus-within:ring-blue-500/20"
        )}
      >
        <Sparkles className="mb-1 size-4 shrink-0 text-blue-400/60" />
        <textarea
          ref={textareaRef}
          id="chat-input"
          value={value}
          onChange={handleInput}
          onKeyDown={handleKeyDown}
          disabled={disabled}
          rows={1}
          placeholder={
            isThinking
              ? "BI-Lite is thinking..."
              : uploadedData
                ? `Ask a question about ${uploadedData.fileName}…`
                : disabled
                  ? "Thinking…"
                  : "Ask a question about your data…"
          }
          className="min-w-0 flex-1 resize-none bg-transparent text-base md:text-sm text-white/90 placeholder-white/25 outline-none disabled:cursor-not-allowed"
          style={{ minHeight: "24px", maxHeight: "180px" }}
        />

        {/* File upload button */}
        {onUpload && !isThinking && (
          <>
            <input
              ref={fileInputRef}
              type="file"
              accept=".csv,.json"
              className="hidden"
              onChange={handleFileChange}
            />
            <button
              type="button"
              onClick={() => fileInputRef.current?.click()}
              disabled={disabled || uploading}
              title="Upload CSV or JSON"
              className={cn(
                "mb-0.5 flex size-8 shrink-0 items-center justify-center rounded-xl transition-all",
                uploading
                  ? "bg-white/10 text-white/40 cursor-wait"
                  : "text-white/30 hover:bg-white/[0.08] hover:text-white/70"
              )}
            >
              {uploading ? (
                <div className="size-3.5 animate-spin rounded-full border-2 border-white/30 border-t-white/80" />
              ) : (
                <Paperclip className="size-3.5" />
              )}
            </button>
          </>
        )}

        {isThinking ? (
          <button
            id="chat-stop-btn"
            type="button"
            onClick={onStop}
            className="mb-0.5 flex size-8 shrink-0 items-center justify-center rounded-xl bg-red-500/20 text-red-400 border border-red-500/30 hover:bg-red-500/30 hover:text-red-300 transition-all active:scale-95 cursor-pointer"
          >
            <div className="bg-white size-2.5 rounded-[2px]" />
          </button>
        ) : (
          <button
            id="chat-send-btn"
            type="button"
            onClick={handleSubmit}
            disabled={!value.trim() || disabled}
            className={cn(
              "mb-0.5 flex size-8 shrink-0 items-center justify-center rounded-xl transition-all active:scale-95",
              value.trim() && !disabled
                ? "bg-gradient-to-br from-blue-500 to-violet-600 text-white shadow-lg shadow-blue-500/20 hover:brightness-110"
                : "bg-white/[0.06] text-white/20 cursor-not-allowed"
            )}
          >
            <Send className="size-3.5" />
          </button>
        )}
      </div>
    </div>
  );
}
