"use client";

import { useRef, useState, useCallback } from "react";
import { Send, Sparkles } from "lucide-react";
import { cn } from "@/lib/utils";

// ---------------------------------------------------------------------------
// Suggestion prompts — shown when the conversation is empty
// ---------------------------------------------------------------------------

const SUGGESTIONS = [
  "Show me a comparison between sales made in January to May in the year 2026",
  "Show me a months vs sales comparison digram",
  "Compare department budgets with their total operational expenses",
  "Show total sales generated by each Associate or Senior Associate",
  "Show the breakdown of expenses by category",
  "Show the monthly sales growth for 2026",
  "What is the total project budget allocated to each department, grouped by project status",
];

interface ChatInputProps {
  onSubmit: (question: string) => void;
  disabled?: boolean;
  showSuggestions?: boolean;
  isThinking?: boolean;
  onStop?: () => void;
}

export function ChatInput({
  onSubmit,
  disabled = false,
  showSuggestions = false,
  isThinking = false,
  onStop,
}: ChatInputProps) {
  const [value, setValue] = useState("");
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  const handleSubmit = useCallback(() => {
    const trimmed = value.trim();
    if (!trimmed || disabled) return;
    onSubmit(trimmed);
    setValue("");
    if (textareaRef.current) {
      textareaRef.current.style.height = "auto";
    }
  }, [value, disabled, onSubmit]);

  const handleSuggestionClick = useCallback((s: string) => {
    setValue(s);
    if (textareaRef.current) {
      textareaRef.current.focus();
      setTimeout(() => {
        if (textareaRef.current) {
          textareaRef.current.style.height = "auto";
          textareaRef.current.style.height = `${Math.min(textareaRef.current.scrollHeight, 180)}px`;
        }
      }, 0);
    }
  }, []);

  function handleKeyDown(e: React.KeyboardEvent<HTMLTextAreaElement>) {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSubmit();
    }
  }

  function handleInput(e: React.ChangeEvent<HTMLTextAreaElement>) {
    setValue(e.target.value);
    const el = e.target;
    el.style.height = "auto";
    el.style.height = `${Math.min(el.scrollHeight, 180)}px`;
  }

  return (
    <div className="flex flex-col gap-3">
      {/* Suggestion chips — only when conversation is empty */}
      {showSuggestions && (
        <div className="flex flex-wrap justify-center gap-2">
          {SUGGESTIONS.map((s) => (
            <button
              key={s}
              onClick={() => handleSuggestionClick(s)}
              disabled={disabled}
              className="rounded-full border border-white/10 bg-white/[0.04] px-3.5 py-1.5 text-xs text-white/50 transition-all hover:border-white/20 hover:bg-white/[0.08] hover:text-white/80 disabled:cursor-not-allowed disabled:opacity-30"
            >
              {s}
            </button>
          ))}
        </div>
      )}

      {/* Input container */}
      <div
        className={cn(
          "relative flex items-end gap-3 rounded-2xl border px-4 py-3 transition-all duration-200",
          disabled && !isThinking
            ? "border-white/[0.06] bg-white/[0.02] opacity-60"
            : "border-white/10 bg-white/[0.05] focus-within:border-blue-500/40 focus-within:bg-white/[0.07] focus-within:ring-1 focus-within:ring-blue-500/20"
        )}
      >
        <Sparkles className="mb-1 size-4 shrink-0 text-blue-400/60" />
        <textarea
          ref={textareaRef}
          id="chat-input"
          value={value}
          onChange={handleInput}
          onKeyDown={handleKeyDown}
          disabled={disabled}
          rows={1}
          placeholder={
            isThinking
              ? "BI-Lite is thinking..."
              : disabled
                ? "Thinking…"
                : "Ask a question about your data…"
          }
          className="min-w-0 flex-1 resize-none bg-transparent text-sm text-white/90 placeholder-white/25 outline-none disabled:cursor-not-allowed"
          style={{ minHeight: "24px", maxHeight: "180px" }}
        />
        {isThinking ? (
          <button
            id="chat-stop-btn"
            type="button"
            onClick={onStop}
            className="mb-0.5 flex size-8 shrink-0 items-center justify-center rounded-xl bg-red-500/20 text-red-400 border border-red-500/30 hover:bg-red-500/30 hover:text-red-300 transition-all active:scale-95 cursor-pointer"
          >
            <div className="bg-white size-2.5 rounded-[2px]" />
          </button>
        ) : (
          <button
            id="chat-send-btn"
            type="button"
            onClick={handleSubmit}
            disabled={!value.trim() || disabled}
            className={cn(
              "mb-0.5 flex size-8 shrink-0 items-center justify-center rounded-xl transition-all active:scale-95",
              value.trim() && !disabled
                ? "bg-gradient-to-br from-blue-500 to-violet-600 text-white shadow-lg shadow-blue-500/20 hover:brightness-110"
                : "bg-white/[0.06] text-white/20 cursor-not-allowed"
            )}
          >
            <Send className="size-3.5" />
          </button>
        )}
      </div>

      <p className="text-center text-[10px] text-white/20">
        Enter to send · Shift+Enter for new line
      </p>
    </div>
  );
}
